//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.REST.Client.TimeServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.digitcyber.com/", ConfigurationName="TimeServices.ITime")]
    public interface ITime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.digitcyber.com/ITime/GetCurrentTime", ReplyAction="http://www.digitcyber.com/ITime/GetCurrentTimeResponse")]
        System.DateTime GetCurrentTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.digitcyber.com/ITime/GetCurrentTime", ReplyAction="http://www.digitcyber.com/ITime/GetCurrentTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetCurrentTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeChannel : WCF.REST.Client.TimeServices.ITime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeClient : System.ServiceModel.ClientBase<WCF.REST.Client.TimeServices.ITime>, WCF.REST.Client.TimeServices.ITime {
        
        public TimeClient() {
        }
        
        public TimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetCurrentTime() {
            return base.Channel.GetCurrentTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetCurrentTimeAsync() {
            return base.Channel.GetCurrentTimeAsync();
        }
    }
}
